baseURL = 'https://notes.pankajniroula.com/'
languageCode = 'en-us'
title = 'CS Notes'
theme = 'hugo-book'

enableGitInfo = true

[params]
    BookTheme = 'auto' 
    BookRepo = 'https://github.com/npankaj365/cs-notes'
    BookCommitPath = 'commit'
    BookEditPath = 'edit/main/'

[markup.goldmark.renderer]
  unsafe = true